# Блок 6. Погружение в Python и анализ данных
## Занятие 6. NumPy: массивы, векторизация и базовая статистика

## Цель занятия

На прошлых занятиях мы изучили функции, модули, классы и начали проект `DataAnalyzer`.

Сначала изучите SOLVED-ноутбук вместе с преподавателем. Затем выполните TODO-ноутбук самостоятельно.

Теперь переходим к библиотеке **NumPy**.

NumPy нужен для быстрой работы с числовыми данными:

- массивы;
- векторные вычисления;
- статистика;
- фильтрация;
- подготовка данных для Pandas и машинного обучения.

---

## Что такое NumPy

`NumPy` — библиотека Python для работы с числовыми массивами.

Обычный список Python:

```python
values = [10, 20, 30]
```

NumPy-массив:

```python
array = np.array([10, 20, 30])
```

NumPy позволяет выполнять операции сразу со всем массивом:

```python
array * 2
```

---

## Практическое значение

NumPy используется:

- в анализе данных;
- в машинном обучении;
- в нейросетях;
- в обработке изображений;
- в статистике;
- в научных расчётах.

---

## Связь с дипломом

В дипломном проекте NumPy пригодится для:

- расчёта средних значений;
- поиска минимумов и максимумов;
- фильтрации числовых данных;
- нормализации признаков;
- подготовки данных к ML.

---

## GitHub

```bash
git checkout main
git pull origin main
git checkout -b feature/block6-lesson06-numpy-basics

git add .
git commit -m "feat: add numpy basics lesson"
git push -u origin feature/block6-lesson06-numpy-basics
```

## Ячейка 1. TODO: импорт NumPy

### Алгоритм

1. Импортируйте `numpy` как `np`.
2. Выведите сообщение.
3. Выведите версию NumPy.
4. Добавьте assert.

In [30]:
# TODO: импортируйте numpy как np
import numpy as np

# TODO: выведите сообщение
print("Numpy подключен")
print("Numpy version", np.__version__)
# TODO: выведите версию NumPy
import sys

assert 'numpy' in sys.modules
# TODO: assert np is not None

Numpy подключен
Numpy version 2.5.2


## Ячейка 2. TODO: создание NumPy-массива

### Алгоритм

1. Создайте обычный список.
2. Преобразуйте его в NumPy-массив.
3. Выведите тип.
4. Проверьте размер.

In [31]:
# TODO: создайте values_list
values_list = [10, 20, 30, 40, 50, 60, 70]
# TODO: создайте values_array = np.array(values_list)
values_array = np.array(values_list)
# TODO: выведите массив и тип
print(values_array)
print(type(values_array))
# TODO: выведите размер
print("Size:", values_array.size)
# TODO: assert

assert values_array.size == len(values_list)

[10 20 30 40 50 60 70]
<class 'numpy.ndarray'>
Size: 7


## Ячейка 3. TODO: векторные операции

### Алгоритм

1. Создайте массив.
2. Умножьте весь массив на 2.
3. Прибавьте 10 ко всем элементам.
4. Проверьте результат.

In [32]:
# TODO: создайте values
values = np.array([10, 100, 1000])
# TODO: создайте double_values
double_values = values * 2
# TODO: создайте plus_values
plus_values = values + 1
# TODO: выведите результаты
print("Source:", values)
print("Doubled:", double_values)
print("Added:", plus_values)
# TODO: assert

assert double_values.tolist() == [20, 200, 2000]
assert plus_values.tolist() == [11, 101, 1001]

Source: [  10  100 1000]
Doubled: [  20  200 2000]
Added: [  11  101 1001]


## Ячейка 4. TODO: базовая статистика

### Алгоритм

1. Создайте массив продаж.
2. Найдите минимум.
3. Найдите максимум.
4. Найдите среднее.
5. Найдите сумму.

In [33]:
# TODO: создайте sales
sales = np.random.default_rng(10).integers(10, 100, 20)

min_value = np.min(sales)
max_value = np.max(sales)
mean_value = np.mean(sales)
sum_value = np.sum(sales)

# TODO: выведите результаты
print("Min", min_value)
print("Max", max_value)
print("Mean", mean_value)
print("Sum", sum_value)

assert min_value == 10
assert max_value == 96
assert mean_value == 56.25
assert sum_value == 1125

Min 10
Max 96
Mean 56.25
Sum 1125


## Ячейка 5. TODO: фильтрация массива

### Алгоритм

1. Создайте массив продаж.
2. Отберите значения больше 170.
3. Выведите результат.
4. Проверьте список.

In [34]:
# TODO: создайте sales
sales = np.random.default_rng(1).integers(100, 300, 10)
# TODO: создайте high_sales
high_sales = sales[sales > 150]
# TODO: выведите high_sales
print("Sales higher 150", high_sales)
# TODO: assert
assert len(high_sales) == 7

Sales higher 150 [194 202 251 290 264 289 162]


## Ячейка 6. TODO: индексация и срезы

### Алгоритм

1. Создайте массив.
2. Получите первый элемент.
3. Получите последний элемент.
4. Получите срез.

In [35]:
# TODO: создайте values
values = np.random.default_rng(2).integers(100, 300, 10)
# TODO: получите first_value
first_value = values[0]
# TODO: получите last_value
last_value = values[-1]
# TODO: получите middle_values
middle_values = values[4:6]
# TODO: выведите результаты
print("First:", first_value)
print("Last:", last_value)
print("Slice:", middle_values)
# TODO: assert
assert first_value == 267
assert last_value == 220
assert middle_values.tolist() == [182, 262]

First: 267
Last: 220
Slice: [182 262]


## Ячейка 7. TODO: двумерный массив

### Алгоритм

1. Создайте двумерный массив 3x3.
2. Выведите форму.
3. Найдите суммы по строкам.
4. Найдите суммы по столбцам.

In [36]:
# TODO: создайте table
table = np.random.default_rng(3).integers(10, 100, size=(3,3))
# TODO: выведите table и table.shape
print(table)
print("Shape:", table.shape)
# TODO: создайте row_sums
row_sums = np.sum(table, axis=1)
# TODO: создайте column_sums
column_sums = np.sum(table, axis=0)
print("Row sums:", row_sums)
print("Column sums:", column_sums)


# TODO: assert
assert table.shape == (3, 3)
assert row_sums.tolist() == [126, 139, 163]
assert column_sums.tolist() == [202, 105, 121]


[[83 17 26]
 [31 26 82]
 [88 62 13]]
Shape: (3, 3)
Row sums: [126 139 163]
Column sums: [202 105 121]


## Ячейка 8. TODO: нормализация данных

### Алгоритм

1. Создайте массив.
2. Найдите минимум и максимум.
3. Приведите значения к диапазону 0–1.
4. Проверьте минимум и максимум.

In [37]:
# TODO: создайте values
values = [i * 100 for i in range(1,10)]
# TODO: создайте normalized
normalized = (values - np.min(values))/(np.max(values) - np.min(values))
# TODO: выведите normalized
print("Source:", values)
print("Normalized:", normalized)
# TODO: assert normalized.min() == 0

# TODO: assert normalized.max() == 1

Source: [100, 200, 300, 400, 500, 600, 700, 800, 900]
Normalized: [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


## Ячейка 9. TODO: NumPy в функции анализа

### Алгоритм

1. Создайте функцию `analyze_array`.
2. Внутри преобразуйте данные в NumPy-массив.
3. Верните словарь со статистикой.
4. Проверьте значения.

In [38]:
# TODO: создайте функцию analyze_array(values)
def analyze_array(values):
    array = np.array(values)
# TODO: внутри создайте array = np.array(values)
    return {
        "min": np.min(array),
        "max": np.max(array),
        "mean": np.mean(array),
        "sum": np.sum(array)
    }
# TODO: верните словарь min, max, mean, sum
vals = np.random.default_rng(5).integers(10, 100, 10)
print(vals)
result = analyze_array(values=vals)
# TODO: вызовите функцию
print(result)
# TODO: assert

[70 82 12 82 52 56 66 35 98 14]
{'min': np.int64(12), 'max': np.int64(98), 'mean': np.float64(56.7), 'sum': np.int64(567)}


## Ячейка 10. TODO: мини-проект занятия

### Алгоритм

1. Создайте массив калорий.
2. Получите статистику через analyze_array.
3. Отфильтруйте высокие нагрузки.
4. Нормализуйте данные.
5. Проверьте результат.

In [40]:
# TODO: создайте calories
calories = np.random.default_rng(6).integers(100, 500, 10)
# TODO: получите stats
stats = analyze_array(calories)
# TODO: создайте high_load
high_load = calories[calories > calories.mean()]
# TODO: создайте normalized_calories
normalized_calories = (calories - calories.min())/(calories.max() - calories.min())
# TODO: выведите результаты
print("Statistic:", stats)
print("High:", high_load)
print("Normalized:", normalized_calories)
# TODO: assert
assert stats["max"] == 494
assert len(high_load) == 3
assert normalized_calories.min() == 0
assert normalized_calories.max() == 1

Statistic: {'min': np.int64(237), 'max': np.int64(494), 'mean': np.float64(324.7), 'sum': np.int64(3247)}
High: [478 363 494]
Normalized: [0.15953307 0.30350195 0.27237354 0.         0.93774319 0.03891051
 0.49027237 0.04669261 0.16342412 1.        ]


# Итог TODO-задания

Покажите преподавателю:

- импорт NumPy;
- создание массива;
- векторные операции;
- статистику;
- фильтрацию;
- индексацию;
- двумерный массив;
- нормализацию;
- функцию анализа;
- мини-проект занятия.

## GitHub

```bash
git add .
git commit -m "feat: complete numpy basics todo"
git push -u origin feature/block6-lesson06-numpy-basics
```